help_texts = {
    "-intro": """
SentryAI Command Line Interface

Usage:
    sentry [command] -[subcommand] [arguments]

Examples:

Authentication:
    sentry auth -login email='test@mail' password='1234'
    > Token generated
    > Token set as default
    > Do you want to use this user_id as default to the next operations? (y/n): n
    > Login successful

Chat creation:
    sentry chat -create name='My first chat'
    > Chat created successfully
    > Do you want to use this chat_id as default to the next operations? (y/n): y

User message creation:
    sentry message -create content='Why is the sky blue?'
    > User message created successfully
    > Do you want to call the AI to respond? (y/n): y
    > AI message created successfully
    > Model 'deepseek-r1:1.5b' said:
    > "The sky appears blue because..."

Tips:
    - You can provide other params such as user_id=x or token=x.
    - Default values are used if no explicit param is provided.
    - Extra parameters are ignored silently.
    - Developers: sending all defaults will not break anything.
""",
    "-auth": """
auth
    -login          Logs in, generates a token and sets it as default.
                    Requires: email (needs to be verified after. An code wil be sent), password
    -googlelogin    Logs in with a google account, or create it if not exists.
                    Requires: google token ID
    -verifyemail    Verifies a registred email
                    Requires: email, code recieved at the email
    -logout         Removes the JWT token from defaults.
                    Takes nothing.
    -gettoken       Prints the current token stored in defaults.
                    Takes nothing.
""",
    "-chat": """
chat
    -create     Creates a chat and optionally sets it as default.
                Requires: name
                Optional: user_id, token
    -get        Gets a chat by ID.
                Requires: chat_id, token
    -getbyuser  Gets all chats from a user.
                Requires: user_id, token
    -getall     Lists all chats.
                Requires: token
    -update     Updates an existing chat.
                Requires: chat_id, token
    -delete     Removes a chat.
                Requires: chat_id, token
    -open       Sets a chat_id as default.
                Requires: chat_id
    -quit       Unsets the default chat_id.
                Takes nothing.
""",
    "-user": """
user
    -create     Creates a new user.
                Requires: name, email, password
                Optional: extra_data
    -get        Gets a user by ID.
                Requires: user_id
    -getall     Lists all users.
                Takes nothing.
    -update     Updates a user.
                Requires: user_id, token
    -delete     Deletes a user.
                Requires: user_id, token
    -open       Sets a user_id as default.
                Requires: user_id
    -quit       Unsets the default user_id.
                Takes nothing.
""",
    "-message": """
message
    -create     Creates a user message.
                Requires: user_id, chat_id, content, token
    -get        Gets a message by ID.
                Requires: user_message_id, token
    -getall     Lists all messages.
                Requires: token
    -getbyuser  Lists all messages from a user.
                Requires: user_id, token
    -getbychat  Lists all messages from a chat.
                Requires: chat_id, token
    -update     Updates a message.
                Requires: user_message_id, token
    -delete     Deletes a message.
                Requires: user_message_id, token
    -open       Sets a user_message_id as default.
                Requires: user_message_id
    -quit       Unsets the default user_message_id.
                Takes nothing.
""",
    "-message_ai": """
message_ai
    -create             Generates an AI response and saves it.
                        Requires: user_id, chat_id, model, token
    -get                Gets an AI message by ID.
                        Requires: ai_message_id, token
    -getall             Lists all AI messages.
                        Requires: token
    -getbychat          Lists all AI messages from a chat.
                        Requires: chat_id, token
    -getbymodel         Lists all AI messages generated by a model.
                        Requires: model_name, token
    -getbychatandmodel  Lists AI messages by chat_id and model.
                        Requires: chat_id, model_name, token
    -update             Updates an AI message.
                        Requires: ai_message_id, token
    -delete             Deletes an AI message.
                        Requires: ai_message_id, token

    -rate               Rates an AI message.
                        Requires: ai_message_id, rating, token
    -getrating          Gets the rating of an AI message.
                        Requires: ai_message_id, token
    -getrated           Lists all AI messages that have ratings.
                        Requires: token
    -feedback           Adds textual feedback to an AI message.
                        Requires: ai_message_id, feedback, token
    -getfeedback        Gets feedbacks of an AI message.
                        Requires: ai_message_id, token

    -open               Sets an ai_message_id as default.
                        Requires: ai_message_id
    -quit               Unsets the default ai_message_id.
                        Takes nothing.
""",
    "-rating": """
rating
    -create     Creates a chat rating.
                Requires: user_id, chat_id, score, token
    -get        Gets a rating by ID.
                Requires: rating_id, token
    -getall     Lists all ratings.
                Requires: token
    -getbyuser  Lists ratings from a user.
                Requires: user_id, token
    -getbychat  Lists ratings from a chat.
                Requires: chat_id, token
    -update     Updates a rating.
                Requires: rating_id, token
    -delete     Deletes a rating.
                Requires: rating_id, token
    -open       Sets a rating_id as default.
                Requires: rating_id
    -quit       Unsets the default rating_id.
                Takes nothing.
""",
    "-contract": """
contract
    -create     Analyzes a contract (alias for -analyze).
                Requires: contract_text, user_id, token
    -analyze    Same as -create (analyzes a contract).
                Requires: contract_text, user_id, token
    -get        Gets a contract by ID.
                Requires: contract_id, token
    -getall     Lists all contracts.
                Requires: token
    -update     Updates a contract.
                Requires: contract_id, token
    -delete     Deletes a contract.
                Requires: contract_id, token
""",
    "-default": """
default
    -get        Gets a default value by key.
                Requires: key
    -getall     Lists all default values.
                Takes nothing.
    -set        Sets a default value.
                Requires: key, value
    -setall     Sets multiple defaults at once.
                Requires: value
    -unset      Removes a default value.
                Requires: key
    -unsetall   Clears all default values.
                Takes nothing.

Recognized default keys:
    auto-create-AI-message   Automatically create AI responses for new user messages. [bool]
    user_id                  Default user ID. [int]
    chat_id                  Default chat ID. [int]
    user_message_id          Default user message ID. [int]
    ai_message_id            Default AI message ID. [int]
    token                    Default JWT token. [string]
    model                    Default model for AI message creation. [string]

Notes:
    You may set any key, but only the above are used internally.
    Keys are case-sensitive.
""",
    "-dashboard": """
Exibits dashboard information on terminal in JSON.
Requires token and user_id.

Information exibited:
kpis:
    active_cases: Number of active chats
    docs_analyzed: Number of documents analyzed
    risks_avoided: Number of risks avoided
    next_deadline: Next important deadline
chart_data: Array containing data from the last 7 days with number of consultations and analyses
history: Latest actions performed
insight: Tip or insight based on the user's last interaction

""",
    "-quit": """
Finishes the execution of the CLI.
uhh.. what did you expect it to do?
""",
    "-help": """
help
    -[command]  Shows help for a specific command.
    -all        Shows help for every command.
""",
}


def get_help(argument: str = None, **kwargs) -> str:
    match argument:
        case "-all":
            return "\n".join(help_texts.values())
        case None:
            return help_texts["-intro"]
        case _ if argument in help_texts:
            return help_texts[argument]
        case _:
            return "No help available for this command."
