"""novas logias para apelacao ao banimento, motivo obrigatorio e detalhado e revisao da apelacao

Revision ID: 27a41f8eb546
Revises: 2b02764e7578
Create Date: 2025-12-07 18:44:09.949498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a41f8eb546'
down_revision = '2b02764e7578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banned_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('appeal_data', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['banned_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('appeal_data')
        batch_op.drop_column('banned_by_id')

    # ### end Alembic commands ###
