"""adding logic and admin router for user banning

Revision ID: 2b02764e7578
Revises: d3d931c8713f
Create Date: 2025-12-07 17:22:51.211970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b02764e7578'
down_revision = 'd3d931c8713f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ban_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('risk_profile_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('risk_profile_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_risk_analysis', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_risk_analysis')
        batch_op.drop_column('risk_profile_summary')
        batch_op.drop_column('risk_profile_score')
        batch_op.drop_column('ban_expires_at')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
