"""adding login API google

Revision ID: 4df17cc14954
Revises: 38fbde2b3f03
Create Date: 2025-12-01 18:59:47.178974

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4df17cc14954"
down_revision = "38fbde2b3f03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("is_verified", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("verification_code", sa.String(length=6), nullable=True)
        )
        batch_op.add_column(
            sa.Column("verification_code_expires_at", sa.DateTime(), nullable=True)
        )
        batch_op.alter_column(
            "password", existing_type=mysql.VARCHAR(length=255), nullable=True
        )
        batch_op.create_unique_constraint(None, ["google_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "password", existing_type=mysql.VARCHAR(length=255), nullable=False
        )
        batch_op.drop_column("verification_code_expires_at")
        batch_op.drop_column("verification_code")
        batch_op.drop_column("is_verified")
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###
